backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "services"
    label: "Services"
    folder: "content/services"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Icon", name: "icon", widget: "string" }
      - { label: "Order", name: "order", widget: "number" }

  - name: "portfolio"
    label: "Portfolio"
    folder: "content/portfolio"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Client", name: "client", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "select", options: ["Social Media", "Web Design", "Brand Identity", "Content Creation"] }
      - { label: "Date", name: "date", widget: "datetime" }

  - name: "pricing"
    label: "Pricing Plans"
    folder: "content/pricing"
    create: true
    fields:
      - { label: "Name", name: "name", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Monthly Price", name: "monthlyPrice", widget: "number" }
      - { label: "Yearly Price", name: "yearlyPrice", widget: "number" }
      - { label: "Is Popular", name: "isPopular", widget: "boolean", default: false }
      - label: "Features"
        name: "features"
        widget: "list"
        fields:
          - { label: "Feature Text", name: "text", widget: "string" }
          - { label: "Included", name: "included", widget: "boolean", default: true }